// Generated by CoffeeScript 1.10.0
(function() {
  (function() {
    var TodoCtrl;
    TodoCtrl = function($scope) {
      var ctrl;
      ctrl = this;
      ctrl.todos = [
        {
          text: "learn angular",
          done: true
        }, {
          text: "buld an angular app",
          done: false
        }
      ];
      ctrl.addTodo = function() {
        ctrl.todos.push({
          text: $scope.todoText,
          done: false
        });
        return $scope.todoText = "";
      };
      ctrl.remaining = function() {
        var count;
        count = 0;
        angular.forEach(ctrl.todos, function(todo) {
          return count += todo.done ? 0 : 1;
        });
        return count;
      };
      ctrl.archive = function() {
        var oldTodos;
        oldTodos = ctrl.todos;
        ctrl.todos = [];
        return angular.forEach(oldTodos, function(todo) {
          if (!todo.done) {
            return ctrl.todos.push(todo);
          }
        });
      };
    };
    return angular.module('myApp.todo', ['ngRoute']).config([
      '$routeProvider', function($routeProvider) {
        $routeProvider.when('/todo', {
          templateUrl: 'todo/todo.html',
          controller: 'TodoCtrl',
          controllerAs: 'ctrl'
        });
      }
    ]).controller('TodoCtrl', TodoCtrl);
  })();

}).call(this);

//# sourceMappingURL=todo.js.map
