// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var TodoCtrl;

  TodoCtrl = (function() {
    function TodoCtrl($scope1) {
      this.$scope = $scope1;
      $scope.todos = [
        {
          text: "learn angular",
          done: true
        }, {
          text: "buld an angular app",
          done: false
        }
      ];
    }

    TodoCtrl.prototype.addTodo = function() {
      this.$scope.todos.push({
        text: this.$scope.todoText,
        done: false
      });
      return this.$scope.todoText = "";
    };

    TodoCtrl.prototype.remaining = function() {
      var count;
      count = 0;
      angular.forEach(this.$scope.todos, function(todo) {
        return count += todo.done ? 0 : 1;
      });
      return count;
    };

    TodoCtrl.prototype.archive = function() {
      var oldTodos;
      oldTodos = this.$scope.todos;
      this.$scope.todos = [];
      return angular.forEach(oldTodos, function(todo) {
        if (!todo.done) {
          return this.$scope.todos.push(todo);
        }
      });
    };

    return TodoCtrl;

  })();

  angular.module('myApp.todo', ['ngRoute']).config([
    '$routeProvider', function($routeProvider) {
      $routeProvider.when('/todo', {
        templateUrl: 'todo/todo.html',
        controller: 'TodoCtrl',
        controllerAs: 'ctrl'
      });
    }
  ]).controller('TodoCtrl', TodoCtrl);

}).call(this);

//# sourceMappingURL=todo.js.map
